todo/main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("", include("task.urls")), path("admin/", admin.site.urls)]

todo/task/urls.py
from django.urls import path


app_name = "task"

#########################################################
# Raw views
#########################################################

from .views import (
    TaskCreateRawView,
    TaskDeleteRawView,
    TaskDetailRawView,
    TaskListRawView,
    TaskUpdateRawView,
)

urlpatterns = [
    path("", TaskListRawView.as_view(), name="index"),
    path("create/", TaskCreateRawView.as_view(), name="create"),
    path("update/<int:id>/", TaskUpdateRawView.as_view(), name="update"),
    path("delete/<int:id>/", TaskDeleteRawView.as_view(), name="delete"),
    path("detail/<int:id>/", TaskDetailRawView.as_view(), name="detail"),
]

# #########################################################
# # Classes based views
# #########################################################

# from .views (
#     TaskCreateView,
#     TaskDeleteView,
#     TaskDetailView,
#     TaskListView,
#     TaskUpdateView
# )

# urlpatterns = [
#     path('', TaskListView.as_view(), name='index'),
#     path('create/', TaskCreateView.as_view(), name='create'),
#     path('update/<int:id>/', TaskUpdateView.as_view(), name='update'),
#     path('delete/<int:id>/', TaskDeleteView.as_view(), name='delete'),
#     path('detail/<int:id>/', TaskDetailView.as_view(), name='detail')
# ]

#########################################################
# Functions based Views
#########################################################

# from .views (
#     list_view,
#     create_view,
#     create_view_raw,
#     update_view ,
#     delete_view,
#     detail_view
# )

# urlpatterns = [
#     path('', list_view, name='index'),
#     path('create/', create_view, name='create'),
#     path('createraw/', create_view_raw, name='createraw'),
#     path('update/<int:id>/', update_view, name='update'),
#     path('delete/<int:id>/', delete_view, name='delete'),
#     path('detail/<int:id>/', detail_view, name='detail')
# ]

todo/templates/base.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>Pixeon Django Doilerplate</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}">
</head>

<body>
    {% include "header.html" %}    
    <div class="ui main text container">
        {% if messages %}        
            {% for message in messages %}
                <div class="ui positive message">
                    <i class="close icon"></i>
                    <div class="header">Success!</div>
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
        {% include "footer.html" %}    
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>
    <script src="{% static 'base/js/script.js' %}"></script>
</body>

</html>

todo/templates/footer.html
<div class="ui footer"><br></div>

todo/templates/header.html
{% include "navbar.html" %}

todo/templates/navbar.html
<div class="ui fixed inverted menu">
    <div class="ui container">
        <a href="{% url 'task:index' %}" class="header item"><i class="tasks icon logo"></i>TODO Application</a>
        <a href="{% url 'task:index' %}" class="item">Home</a>
        <div class="ui simple dropdown item">
            Tasks <i class="dropdown icon"></i>
            <div class="menu">
                <a class="item" href="{% url 'task:create' %}">Create</a>                         
            </div>
        </div>
    </div>
</div>